name: biometry
description: A Flutter package for integrating with the Biometry API to provide biometric authentication and verification services.
version: 0.1.3
homepage: https://biometrysolutions.com

environment:
  sdk: ">=2.12.0 <3.7.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.14
  build_runner_core: ^8.0.0
  logging: ^1.3.0
  json_serializable: ^6.9.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
